[package]
name = "aireality2rustdemo"
version = "0.1.10"
authors = []
edition = "2021"

[lib]
name = "aireality2rustdemo"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
