#!/bin/bash

cd ..

RELEASE=$(awk -F'"' '/version:/ {print $2}' mix.exs)
ARCH=$(uname -m)
OS=$(uname -o | sed 's/\//_/g')
BUILD_FOLDER=${ARCH}_${OS}

echo "********************************************************************"
echo "Building Reality2 Node version ${RELEASE} for ${BUILD_FOLDER} ..."
echo "********************************************************************"

echo "***** Cleaning up the previous build..."
rm -rf "_build/prod"
rm -rf "builds"

if [ ! -d "builds" ]; then
    mkdir "builds"
fi
if [ ! -d "builds/${BUILD_FOLDER}" ]; then
    mkdir "builds/${BUILD_FOLDER}"
fi

echo "***** Generating new Certificates..."
cd apps/reality2_web
mix phx.gen.cert
cd ../..

# Set the environment variables
# export DATABASE_URL="ecto://postgres:postgres@localhost/reality2"
export SECRET_KEY_BASE=$(openssl rand -hex 32)
export PORT=4005
export POOLSIZE=10
export MIX_ENV=prod
export PLUGINS="ai.reality2.vars, ai.reality2.geospatial, ai.reality2.pns, ai.reality2.auth, ai.reality2.backup, ai.reality2.rustdemo"

# Get any new deps
mix deps.get

# Build the Reality2 Node
echo "***** Building the Reality2 Node..."
mix release

# echo "***** Copying the Reality2 Demos to the release directory..."
cp "scripts/runtime_run" "_build/prod/rel/reality2/run"
# cp -r demos/python "_build/prod/rel/reality2"
# cp -r demos/SBC "_build/prod/rel/reality2"

echo "***** Adding some useful extras..."
cp -r extras "_build/prod/rel/reality2"

echo "***** Creating the Reality2 Node tarball..."
tar -zcf "_build/prod/rel/reality2_${RELEASE}.tar.gz" --directory=_build/prod/rel reality2

echo "***** Moving the Reality2 Node tarball to the builds directory..."
mv "_build/prod/rel/reality2_${RELEASE}.tar.gz" "builds/${BUILD_FOLDER}"

echo "***** Making a zip file for loading to GitHub..."
cd "builds"
zip -r "${BUILD_FOLDER}.zip" "${BUILD_FOLDER}"

echo "***** Cleaning up..."
rm -rf "${BUILD_FOLDER}"

echo "********************************************************************"
echo "Reality2 Node version ${RELEASE} for ${BUILD_FOLDER} has been built."
echo "********************************************************************"
