#!/bin/bash
cd ..

RELEASE=$(awk -F'"' '/version:/ {print $2}' mix.exs)
ARCH=$(uname -m)
OS=$(uname -o | sed 's/\//_/g')
BUILD_FOLDER=${ARCH}_${OS}

arch=$(uname -m)
os=$(uname -o)

if [ ! -d "builds" ]; then
    mkdir "builds"
fi
if [ ! -d "builds/${BUILD_FOLDER}" ]; then
    mkdir "builds/${BUILD_FOLDER}"
fi

echo "********************************************************************"
echo "Building Reality2 Node version ${RELEASE} for ${BUILD_FOLDER} ..."
echo "********************************************************************"

rm -rf "_build/prod"

# Set the environment variables
export DATABASE_URL="ecto://postgres:postgres@localhost/reality2"
export SECRET_KEY_BASE=$(openssl rand -hex 32)
export PORT=4001
export POOLSIZE=10
export MIX_ENV=prod

# Build the Reality2 Node
echo "Building the Reality2 Node..."
mix release

echo "Copying the Reality2 Node to the release directory..."
cp "scripts/runtime_run" "_build/prod/rel/reality2/run"
cp -r python "_build/prod/rel/reality2"

echo "Creating the Reality2 Node tarball..."
tar -zcf "_build/prod/rel/reality2_${RELEASE}.tar.gz" --directory=_build/prod/rel reality2

echo "Moving the Reality2 Node tarball to the builds directory..."
mv "_build/prod/rel/reality2_${RELEASE}.tar.gz" "builds/${BUILD_FOLDER}"

echo "********************************************************************"
echo "Reality2 Node version ${RELEASE} for ${BUILD_FOLDER} has been built."
echo "********************************************************************"
