#!/bin/bash
export NODENAME="reality2@server"
export MIX_ENV=prod

if ! [ -d "scripts" ]; then
  cd ..
fi

# Set the environment variable
# export DATABASE_URL="ecto://postgres:postgres@localhost/reality2"
export SECRET_KEY_BASE=$(openssl rand -hex 32)
export PORT=4001
export POOLSIZE=10

# Create the mnesia directory structure if it doesn't exist
if ! [ -d ".mnesia" ]; then
  mkdir .mnesia
fi
cd .mnesia
if ! [ -d $MIX_ENV ]; then
  mkdir $MIX_ENV
fi
cd $MIX_ENV
if ! [ -d $NODENAME ]; then
  mkdir $NODENAME
fi
cd ../..

# Start the Elixir application
iex --name $NODENAME -S mix phx.server
