#!/bin/bash
export MIX_ENV=dev
#export PLUGINS="ai.reality2.vars, ai.reality2.geospatial, ai.reality2.pns, ai.reality2.auth, ai.reality2.backup, ai.reality2.rustdemo"
export PLUGINS="ai.reality2.vars, ai.reality2.geospatial, ai.reality2.backup, ai.reality2.rustdemo, ai.reality2.transnet"

# If in the Scripts directory, move up one level
if ! [ -d "scripts" ]; then
  cd ..
fi

# Create the mnesia directory structure if it doesn't exist
if ! [ -d ".mnesia" ]; then
  mkdir ".mnesia"
fi
cd .mnesia
if ! [ -d $MIX_ENV ]; then
  mkdir $MIX_ENV
fi
cd ..

# Get any new deps
mix deps.get

# Force reality2_web to be recompiled in case there have been some new WebApps added
rm -rf _build/dev/lib/reality2_web

# Start the Elixir application
iex -S mix phx.server
