#!/bin/bash

# Set the environment variables
# export DATABASE_URL="ecto://postgres:postgres@localhost/reality2"
export SECRET_KEY_BASE=$(openssl rand -hex 32)
export PORT=4005
export POOLSIZE=10
export MIX_ENV=prod
export VERSION=$(bin/reality2 version)
#export PLUGINS="ai.reality2.vars, ai.reality2.geospatial, ai.reality2.pns, ai.reality2.auth, ai.reality2.backup, ai.reality2.rustdemo"
export PLUGINS="ai.reality2.vars, ai.reality2.geospatial, ai.reality2.backup, ai.reality2.rustdemo, ai.reality2.transnet"

# Change to given directory (if passed in)
if [ -n "$1" ]; then
  cd $1
fi

# Create the mnesia directory structure if it doesn't exist
if ! [ -d ".mnesia" ]; then
  mkdir ".mnesia"
fi
cd .mnesia
if ! [ -d $MIX_ENV ]; then
  mkdir $MIX_ENV
fi
cd ..

# Run the Reality2 Node
echo "**************************************"
echo "Running: ${VERSION}"
echo "**************************************"

bin/reality2 start
